version: '2'
services:
    nginx:
        build: ./nginx/
        container_name: nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - app
    php:
        build: ./php/
        container_name: php
        expose:
            - 9000
        links:
            - mysql
        volumes_from:
            - app
    app:
        image: php:5.6-fpm
        container_name: app
        volumes:
            - path/to/app:/var/www/application
        command: "true"
    mysql:
        build: ./mysql/
        container_name: mysql
        volumes_from:
            - data
        environment:
            - MYSQL_ROOT_PASSWORD="rootpassword"
            - MYSQL_DATABASE="dbname"
            - MYSQL_USER="username"
            - MYSQL_PASSWORD="password"
    data:
        image: mysql:5.6
        volumes:
            - ./mysql/data/mysql:/var/lib/mysql
            - ./mysql/data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        command: "true"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - mysql
        environment:
            - PMA_HOST="mysql"
